name: CI Github Pages
on:
  #监听push操作
  push:
    branches:
      - main # 这里只配置了main分支，所以只有推送main分支才会触发以下任务
permissions:
  contents: write
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 官方action，将代码拉取到虚拟机
      - name: Checkout  ️ 
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Print Current Directory
        run: |
          cd insomnia-web
          tree -L 1
          npm install
          npm run build
          tree -L 1


      - name: Deploy   # 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: github-pages # 部署后提交到那个分支
          folder: insomnia-web/dist # 这里填打包好的目录名称
